### ISSUE TITLE
wgrep install failed

### ISSUE THREAD

**Issue by xinglongcui** [stav/wgrep#4]
p4@p4:~/GitHub/wgrep$ sudo npm install -g
loadDep:puppeteer → resol ▐ ╢█████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:ws → 304          ▄ ╢██████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
/usr/local/bin/wgrep -> /usr/local/lib/node_modules/wgrep/index.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/wgrep/node_modules/puppeteer
> node install.js

/usr/local/lib/node_modules/wgrep/node_modules/puppeteer/install.js:78
  return Promise.all([...cleanupOldVersions, generateProtocolTypesIfNecessary(true /* updated */)]);
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.0-146-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/p4/GitHub/wgrep/npm-debug.log
npm ERR! code 1

p4@p4:~/GitHub/wgrep$ uname -a
Linux p4 4.4.0-146-generic #172-Ubuntu SMP Wed Apr 3 09:00:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xinglongcui** [comment]
Fixed This Problem on Windows WSL ubuntu
But I still don't know why

**Comment by stav** [comment]
Thanks for reporting.  I finally merged a pull request to fix a missing dependency which seems unrelated to your issue.
