### ISSUE TITLE
wgrep stav https://github.com/stav/wgrep generate runtime error 

### ISSUE THREAD

**Issue by Dorian-Ba** [stav/wgrep#8]
[
![Capture](https://user-images.githubusercontent.com/49530244/94815865-b0a5c900-0403-11eb-8f78-266b0f2a6054.PNG)
](url)

**Comment by Dorian-Ba** [comment]
wgrep stav https://github.com/stav/wgrep generates runtime error

**Comment by stav** [comment]
Thanks for reporting @Dorian-Ba.  Are  you using `node`?  What version?

What is the output of:

    node -v
